### ISSUE TITLE
A recommandation for resources on KBQA and LLM 

### ISSUE THREAD

**Issue by StauskasCST** [zjukg/KG-LLM-Papers#10]
Hi there,
      We just proposed MarkQA: a large scale KBQA dataset with numerial reasoning, which is accepted by EMNLP 2023. 
      We also provided a e step-by-step symbolic reasoning path called PyQL in the MarkQA to help facilitate the multi-hop and numerical reasoning.
     Here is our paper: https://arxiv.org/abs/2310.15517
     Thank you for your time!

**Comment by hackerchenzhuo** [comment]
@StauskasCST Thanks for your recommandation. 

Nice work!

**Comment by StauskasCST** [comment]
Hi Zhuo,
&nbsp; &nbsp; Thanks for your attention!&nbsp;
&nbsp; &nbsp; Sorry to interrupt but MarkQA should better be place in resources and benchmark track.
&nbsp; &nbsp; Thank you again for your time!


Yours,
Sitao






Sitao&nbsp;"Tony"&nbsp;Cheng
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/KG-LLM-Papers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 晚上11:20
***@***.***&gt;;
抄送:&nbsp;"Sitao "Tony" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/KG-LLM-Papers] A recommandation for resources on KBQA and LLM  (Issue #10)





 
@StauskasCST Thanks for your recommandation.
 
Nice work!

**Comment by hackerchenzhuo** [comment]
Thanks for your reminder.
