### ISSUE TITLE
A paper similar to this research direction

### ISSUE THREAD

**Issue by zhiqix** [zjukg/KG-LLM-Papers#14]
Hello！Your work is so great! We have an article about the combination of knowledge graphs and Foundation Models: R3-NL2GQL: A Hybrid Models Approach for Accuracy Enhancement and Hallucinations Mitigation. It is a method that uses a combination of larger and smaller models to generate graph database query language and retrieve the graph context required for the LLM, which is similar to your research direction.
The address of the paper is: https://arxiv.org/abs/2311.01862
The open source address for the code and dataset is: https://github.com/zhiqix/nl2gql
If you are interested, welcome to provide valuable feedback! Thank you for your time!

**Comment by hackerchenzhuo** [comment]
Thank you for your kind words, and great job! We welcome your future contributions to this project through pull requests. 

Looking forward to your future contributions!
