### ISSUE TITLE
A framework to employ LLMs for entity alignment in knowledge graphs

### ISSUE THREAD

**Issue by chensyCN** [zjukg/KG-LLM-Papers#26]
- \[[arxiv](https://arxiv.org/abs/2405.16806)\] Entity Alignment with Noisy Annotations from Large Language Models. \[[code](https://github.com/chensyCN/llm4ea_official)\]

**Comment by hackerchenzhuo** [comment]
Please submit the relevant PR directly to the repository. Thanks.
