### ISSUE TITLE
[Discussion] Share Your Paper Resources

### ISSUE THREAD

**Issue by pavaris-pm** [zjukg/KG-LLM-Papers#8]
I just want to ask all contributors here about how you gather these **LLM-KG research papers**, since many papers is very fresh and up-to-date. I think it would be great to have a discussion about it (i did not see a discussion tab here, so, i made an issue in this repo instead). Here is what i want to ask:

1. The sources or methods you use to find `up-to-date` research papers. This could include online databases, websites, newsletters, academic journals, or any other resources you find useful.

2. If you use any specific tools, scripts, or search queries to streamline the process of discovering new papers, please provide details or examples.

3. Any tips or best practices you have found effective in finding the most relevant and `up-to-date` papers.

with that, i think it would help all of us to take a look and update new papers related faster.

Thank you all in advance.

**Comment by hackerchenzhuo** [comment]
Thank you for your questions, but we don't actually use any tools. The update will occur simply when students share relevant papers during weekly group meetings. 

Students have different methods for finding their papers.

Best wishes,
Zhuo

**Comment by pavaris-pm** [comment]
Thank you! I got it. Hope that it will be updated weekly!
